using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using SMP1;
namespace smp.PL
{
    public partial class FormPurchases : Form
    {
        DB_SMPEntities3 db= new DB_SMPEntities3();
        public FormPurchases()
        {
            InitializeComponent();

           
            // This line of code is generated by Data Source Configuration Wizard
            gridControl1.DataSource = new SMP1.DB_SMPEntities3().TB_PUR;
        }
        
        private void simpleButton22_Click(object sender, EventArgs e)
        {
            SMP1.PL.FRM_PUR frm = new SMP1.PL.FRM_PUR();
            frm.id = 1;
            frm.simpleButton1.Text = "Add";
            frm.Text = "Add";
            frm.ShowDialog();
            update();
        }
      
        private void simpleButton1_Click(object sender, EventArgs e)
        {
            try
            {
                SMP1.PL.FRM_PUR frm = new SMP1.PL.FRM_PUR();
                frm.id = 2;
                frm.simpleButton1.Text = "Edit";
                frm.Text = "Edit";
                TB_PUR tb = new TB_PUR();
                int id = frm.id1 = Convert.ToInt32(gridView1.GetFocusedRowCellValue("ID"));
                db = new DB_SMPEntities3();
                tb = db.TB_PUR.Where(x => x.ID == id).FirstOrDefault();
                frm.ebt_name.Text = tb.Pur_Name;
                frm.textBox1.Text = tb.Pur_Type;
                frm.str1 = tb.Pur_Cat;
                frm.str2 = tb.Pur_Supp;
                frm.textBox2.Text = tb.Pur_Det;
                frm.textboxp.Text = tb.Pur_Buy.ToString();
                frm.textBoxs.Text = tb.Pur_Sell.ToString();
                frm.spinEditq.Value = Convert.ToDecimal(tb.Pur_Qt);
                frm.ShowDialog();
                update();
                Close();
            }
            catch { }
        }

        private void simpleButton3_Click(object sender, EventArgs e)
        {
            
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            int id = Convert.ToInt32(gridView1.GetFocusedRowCellValue("ID"));
            if (id == default(int))
            {
                SMP1.EPL.Toast toast = new SMP1.EPL.Toast();
                toast.label1.Text = "There is no purchase to remove\n(the grid control is empty)";
                toast.Show();
                return;
            }

                MessageBoxButtons mb = MessageBoxButtons.YesNo;
                DialogResult = MessageBox.Show("Are you sure you want to remove this purchase", "Delete Purchase", mb);
                if (DialogResult == DialogResult.Yes)
                {
                    db = new DB_SMPEntities3();
                    TB_PUR tb = new TB_PUR();
                    tb = db.TB_PUR.Where(x => x.ID == id).FirstOrDefault();
                    db.TB_PUR.DeleteObject(tb);
                    db.SaveChanges();
                    update();
                }
            
           
        }
        void update()
        {
            db = new DB_SMPEntities3();
            gridControl1.DataSource = db.TB_PUR.ToList();
        
        }
        private void textBox1_TextChanged(object sender, EventArgs e)
        {
            try
            {
                string str = textBox1.Text;
                if (radioButton1.Checked == true) gridControl1.DataSource = db.TB_PUR.Where(x => x.Pur_Name.Contains(str)).ToList();
                if (radioButton2.Checked == true) gridControl1.DataSource = db.TB_PUR.Where(x => x.Pur_Type.Contains(str)).ToList();
                if (radioButton3.Checked == true) gridControl1.DataSource = db.TB_PUR.Where(x => x.Pur_Det.Contains(str)).ToList();
                if (radioButton6.Checked == true) gridControl1.DataSource = db.TB_PUR.Where(x => x.Pur_Cat .Contains(str)).ToList();
                if (radioButton7.Checked == true) gridControl1.DataSource = db.TB_PUR.Where(x => x.Pur_Supp.Contains(str)).ToList();
            }
            catch {}
            if (textBox1.Text != "") simpleButton4.Visible = true;
            else simpleButton4.Visible = false;

        }

        private void simpleButton4_Click(object sender, EventArgs e)
        {
            if (!simpleButton4.Visible) return;
            textBox1.Text = "";
            simpleButton4.Visible = false;
        }

        private void FormCategory_Load(object sender, EventArgs e)
        {
            
        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

        private void callrch(object sender, EventArgs e)
        {
            textBox1_TextChanged(sender, e);
        }
    }
}
