using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using SMP1;
namespace smp.PL
{
    public partial class FormCategory : Form
    {
       DB_SMPEntities3 db = new DB_SMPEntities3();
       TB_CAT tb = new TB_CAT();
        public FormCategory()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard


            // This line of code is generated by Data Source Configuration Wizard
            gridControl1.DataSource = new SMP1.DB_SMPEntities3().TB_CAT;
        }
        
        private void simpleButton22_Click(object sender, EventArgs e)
        {
            SMP1.PL.FRM_CAT_ADD op = new SMP1.PL.FRM_CAT_ADD();
            op.id = 0;
            op.Text = "ADD";
            op.btn_add.Text ="Add";
            op.ShowDialog();
            db = new DB_SMPEntities3();
            gridControl1.DataSource = db.TB_CAT.ToList();
         
        }
        SMP1.PL.FRM_CAT_ADD op = new SMP1.PL.FRM_CAT_ADD();
        private void simpleButton1_Click(object sender, EventArgs e)
        {
            try
            {
                op.id1 = Convert.ToInt32(layoutView1.GetFocusedRowCellValue("ID"));
                tb = db.TB_CAT.Where(x => x.ID == op.id1).FirstOrDefault();
                SMP1.LB.Methods method = new SMP1.LB.Methods();
                string str = tb.CAT_Name.ToString();
                method.bit = tb.CAT_Cover;
                op.ebt_name.Text = str;
                op.pic_cover.Image = Image.FromStream(method.ToImage());
                op.id = 1;
                op.Text = "EDIT";
                op.btn_add.Text = "Edit";
                op.ShowDialog();
                update();
            }
            catch { };
        }

        private void simpleButton3_Click(object sender, EventArgs e)
        {
            db = new DB_SMPEntities3();
            
            gridControl1.DataSource = db.TB_CAT.ToList();
            textBox1.Text = "";
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            //Delete
            try
            {
                int id = Convert.ToInt32(layoutView1.GetFocusedRowCellValue("ID"));
                if (id == default(int)) 
                {
                    SMP1.EPL.Toast toast = new SMP1.EPL.Toast();
                    toast.label1.Text = "There are no categorys to remove\n(The grid control is empty)";
                    toast.Show();
                    return;
                }
                MessageBoxButtons mbutton = MessageBoxButtons.YesNo;
                DialogResult = MessageBox.Show("Are you sure you want to remove this category", "Delete Catergory", mbutton);
                if (DialogResult == DialogResult.Yes)
                {
                    tb = db.TB_CAT.Where(x => x.ID == id).FirstOrDefault();
                    db.DeleteObject(tb);
                    db.SaveChanges();
                    update();
                }
                
            }
            catch { }
        }
        void update()
        {
            db = new DB_SMPEntities3();
            try
            {
                string ts = textBox1.Text;
                gridControl1.DataSource = db.TB_CAT.Where(x => x.CAT_Name.Contains(textBox1.Text)).ToList();
            }
            catch { }
         
        }

        private void textBox1_TextChanged(object sender, EventArgs e)
        {
           
        }

        private void simpleButton4_Click(object sender, EventArgs e)
        {
           
        }

        private void textBox1_TextChanged_1(object sender, EventArgs e)
        {
            string ts = textBox1.Text;
            try
            {

                gridControl1.DataSource = db.TB_CAT.Where(x => x.CAT_Name.Contains(textBox1.Text)).ToList();
            }
            catch { }
            if (ts == "") simpleButton4.Visible = false;
            else simpleButton4.Visible = true;
        }

        private void simpleButton4_Click_1(object sender, EventArgs e)
        {
            if (!simpleButton1.Visible) return;
            textBox1.Text = "";

            simpleButton4.Visible = false;
        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

        private void FormCategory_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyValue == 46) simpleButton2_Click(simpleButton2, e);
        }

        private void FormCategory_Load(object sender, EventArgs e)
        {

        }
    }
}
