using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using SMP1;
namespace smp.PL
{
    public partial class FormSale : Form
    {
        DB_SMPEntities3 db= new DB_SMPEntities3();
        public FormSale()
        {
            InitializeComponent();


            // This line of code is generated by Data Source Configuration Wizard
          
            // This line of code is generated by Data Source Configuration Wizard
            gridControl1.DataSource = new SMP1.DB_SMPEntities3().TB_SELL;
        }
        
        private void simpleButton22_Click(object sender, EventArgs e)
        {
            SMP1.PL.FRM_SAL frm = new SMP1.PL.FRM_SAL();
            frm.id = 1;
            frm.simpleButton1.Text = "Add";
            frm.Text = "Add";
            frm.ShowDialog();
            update();
        }
      
        private void simpleButton1_Click(object sender, EventArgs e)
        {
            try
            {
                
                SMP1.PL.FRM_SAL frm = new SMP1.PL.FRM_SAL();
                frm.Text = "Edit";
                frm.simpleButton1.Text = "Edit";
                frm.id =2;
                int id=frm.id1 = Convert.ToInt32(gridView1.GetFocusedRowCellValue("ID"));
                TB_SELL tb = new TB_SELL();
                tb = db.TB_SELL.Where(x => x.ID == frm.id1).FirstOrDefault();
                frm.str1= tb.Sell_Name;
                frm.str2 = tb.Sell_Cus;
                frm.q01= Convert.ToDecimal( tb.Sell_Qt);
                frm.ShowDialog();
                update();
                Close();
            }
            catch { }
        }

        private void simpleButton3_Click(object sender, EventArgs e)
        {
            
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            int id = Convert.ToInt32(gridView1.GetFocusedRowCellValue("ID"));
            if (id == default(int))
            {
                SMP1.EPL.Toast toast = new SMP1.EPL.Toast();
                toast.label1.Text = "There is no Sale to remove\n(the grid control is empty)";
                toast.Show();
                return;
            }

                MessageBoxButtons mb = MessageBoxButtons.YesNo;
                DialogResult = MessageBox.Show("Are you sure you want to remove this Sale", "Delete Salle", mb);
                if (DialogResult == DialogResult.Yes)
                {
                    db = new DB_SMPEntities3();
                    TB_SELL tb = new TB_SELL();
                    tb = db.TB_SELL.Where(x => x.ID == id).FirstOrDefault();
                    db.TB_SELL.DeleteObject(tb);
                    db.SaveChanges();
                    update();
                }
            
           
        }
        void update()
        {
            db = new DB_SMPEntities3();
            gridControl1.DataSource = db.TB_SELL.ToList();
        
        }
        private void textBox1_TextChanged(object sender, EventArgs e)
        {
            try
            {
                string str = textBox1.Text;
                if (radioButton1.Checked == true) gridControl1.DataSource = db.TB_SELL.Where(x => x.Sell_Name.Contains(str)).ToList();
                if (radioButton2.Checked == true) gridControl1.DataSource = db.TB_SELL.Where(x => x.Sell_Cus.Contains(str)).ToList();
                if (radioButton3.Checked == true) gridControl1.DataSource = db.TB_SELL.Where(x => x.Sell_Date.ToString().Contains(str)).ToList();
                if (radioButton6.Checked == true) gridControl1.DataSource = db.TB_SELL.Where(x => x.Sell_Qt.ToString().Contains(str)).ToList();
                if (radioButton7.Checked == true) gridControl1.DataSource = db.TB_SELL.Where(x => x.Sell_Price.ToString().Contains(str)).ToList();
            }
            catch {}
            if (textBox1.Text != "") simpleButton4.Visible = true;
            else simpleButton4.Visible = false;

        }

        private void simpleButton4_Click(object sender, EventArgs e)
        {
            if (!simpleButton4.Visible) return;
            textBox1.Text = "";
            simpleButton4.Visible = false;
        }

        private void FormCategory_Load(object sender, EventArgs e)
        {
            
        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

        private void callrch(object sender, EventArgs e)
        {
            textBox1_TextChanged(sender, e);
        }
    }
}
