using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using SMP1;
namespace smp.PL
{
    public partial class FormSupplier : Form
    {
        DB_SMPEntities3 db= new DB_SMPEntities3();
        SMP1.EPL.Toast toast;
        public FormSupplier()
        {
            InitializeComponent();


            // This line of code is generated by Data Source Configuration Wizard
           
            // This line of code is generated by Data Source Configuration Wizard
            gridControl1.DataSource = new SMP1.DB_SMPEntities3().TB_SUP;
        }
        
        private void simpleButton22_Click(object sender, EventArgs e)
        {
            SMP1.PL.FRM_SUP formadd = new SMP1.PL.FRM_SUP();
            formadd.id = 1;
            formadd.btn_add.Text = "Add";
            formadd.Text = "ADD";
            formadd.ShowDialog();
            update();
         
        }
      
        private void simpleButton1_Click(object sender, EventArgs e)
        {
            try
            {
                SMP1.LB.Methods method = new SMP1.LB.Methods();
                SMP1.PL.FRM_SUP formadd = new SMP1.PL.FRM_SUP();
                formadd.id = 2;
                formadd.key = Convert.ToInt32(layoutView1.GetFocusedRowCellValue("ID"));
                TB_SUP tb = new TB_SUP();
                db = new DB_SMPEntities3();
                tb = db.TB_SUP.Where(x => x.ID == formadd.key).FirstOrDefault();
                method.bit = tb.Sup_Image;
                formadd.pic_cover.Image = Image.FromStream(method.ToImage());
                formadd.ebt_name.Text = tb.Sup_Name;
                formadd.textBox1.Text = tb.Sup_Phone;
                formadd.textBox2.Text = tb.Sup_Email;
                formadd.btn_add.Text = "EDIT";
                formadd.Text = "Edit";
                formadd.ShowDialog();
                update();
            }
            catch { }
            
        }

        private void simpleButton3_Click(object sender, EventArgs e)
        {
            update();
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
           
            try
            {
                int id = Convert.ToInt32(layoutView1.GetFocusedRowCellValue("ID"));
                if (id == default(int))
                { 
                    toast = new SMP1.EPL.Toast();
                    toast.label1.Text = "there is no supplier to remove\n( the grid control is empty)";
                    toast.Show();
                    return;
                }
                MessageBoxButtons mbutton = MessageBoxButtons.YesNo;
                DialogResult = MessageBox.Show("Are you sure you want to remove this supplier","Delete Supplers", mbutton);
                if (DialogResult == DialogResult.No) return;
                TB_SUP tb = new TB_SUP();
               
                tb = db.TB_SUP.Where(x => x.ID == id).FirstOrDefault();
                db.TB_SUP.DeleteObject(tb);
                db.SaveChanges();
                update();
            }
            catch
            {
                
            }
           
        }
        void update()
        {

            db = new DB_SMPEntities3();
            gridControl1.DataSource = db.TB_SUP.ToList();

        }

        private void textBox1_TextChanged(object sender, EventArgs e)
        {
            string str = textBox1.Text;
            if(radioButton1.Checked==true) gridControl1.DataSource = db.TB_SUP.Where(x => x.Sup_Name.Contains(str)).ToList();
            if (radioButton2.Checked == true) gridControl1.DataSource = db.TB_SUP.Where(x => x.Sup_Phone.Contains(str)).ToList();
            if(radioButton3.Checked==true) gridControl1.DataSource = db.TB_SUP.Where(x => x.Sup_Email.Contains(str)).ToList();
            if (textBox1.Text == "") simpleButton4.Visible = false;
            else simpleButton4.Visible = true;
          
        }

        private void simpleButton4_Click(object sender, EventArgs e)
        {
            if (!simpleButton1.Visible) return;
            textBox1.Text = "";
          
            simpleButton4.Visible = false;
        }

        private void FormCategory_Load(object sender, EventArgs e)
        {
            
        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

        private void callrch(object sender, EventArgs e)
        {
            textBox1_TextChanged(sender, e);
        }
    }
}
