using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using SMP1;
namespace smp.PL
{
    public partial class FormUser : Form
    {
        DB_SMPEntities3 db= new DB_SMPEntities3();
        SMP1.EPL.Toast toast;
        public FormUser()
        {
            InitializeComponent();


            // This line of code is generated by Data Source Configuration Wizard

            // This line of code is generated by Data Source Configuration Wizard

            
            gridControl1.DataSource = new SMP1.DB_SMPEntities3().TBUSERs;
        }
        
        private void simpleButton22_Click(object sender, EventArgs e)
        {
            SMP1.PL.FRM_USE formadd = new SMP1.PL.FRM_USE();
            formadd.id = 1;
            formadd.btn_add.Text = "Add";
            formadd.Text = "ADD";
            formadd.ShowDialog();
            update();
         
        }
      
        private void simpleButton1_Click(object sender, EventArgs e)
        {
            try
            {
                SMP1.LB.Methods method = new SMP1.LB.Methods();
                SMP1.PL.FRM_USE formadd = new SMP1.PL.FRM_USE();
                formadd.id = 2;
                formadd.key = Convert.ToInt32(gridView1.GetFocusedRowCellValue("ID"));
                TBUSER tb = new TBUSER();
                db = new DB_SMPEntities3();
                
                tb = db.TBUSERs.Where(x => x.ID == formadd.key).FirstOrDefault();
                method.bit = tb.Image;
                formadd.pic_cover.Image = Image.FromStream(method.ToImage());
                formadd.ebt_name.Text = tb.Username;
                formadd.textBox1.Text = tb.Password;
                formadd.comboBox1.Text = tb.Rol;
                formadd.btn_add.Text = "EDIT";
                formadd.Text = "Edit";
                formadd.ShowDialog();
                update();
            }
            catch { }
            
        }

        private void simpleButton3_Click(object sender, EventArgs e)
        {
            update();
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
           
            try
            {
                int id = Convert.ToInt32(gridView1.GetFocusedRowCellValue("ID"));
                if (id == default(int))
                { 
                    toast = new SMP1.EPL.Toast();
                    toast.label1.Text = "there is no User to remove\n( the grid control is empty)";
                    toast.Show();
                    return;
                }
                MessageBoxButtons mbutton = MessageBoxButtons.YesNo;
                DialogResult = MessageBox.Show("Are you sure you want to remove this User","Delete User", mbutton);
                if (DialogResult == DialogResult.No) return;
                TBUSER tb = new TBUSER();
               
                tb = db.TBUSERs.Where(x => x.ID == id).FirstOrDefault();
                db.TBUSERs.DeleteObject(tb);
                db.SaveChanges();
                update();
            }
            catch
            {
                
            }
           
        }
        void update()
        {

            db = new DB_SMPEntities3();
            gridControl1.DataSource = db.TBUSERs.ToList();

        }

        private void textBox1_TextChanged(object sender, EventArgs e)
        {
           
          
        }

        private void simpleButton4_Click(object sender, EventArgs e)
        {
           
        }

        private void FormCategory_Load(object sender, EventArgs e)
        {
            
        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

        private void callrch(object sender, EventArgs e)
        {
           
        }
    }
}
