//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DB_SMPModel", "FK_TB_PUR_TB_CAT", "TB_CAT", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SMP1.TB_CAT), "TB_PUR", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SMP1.TB_PUR), true)]
[assembly: EdmRelationshipAttribute("DB_SMPModel", "FK_TB_PUR_TB_SUP", "TB_SUP", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SMP1.TB_SUP), "TB_PUR", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SMP1.TB_PUR), true)]

#endregion

namespace SMP1
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DB_SMPEntities3 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DB_SMPEntities3 object using the connection string found in the 'DB_SMPEntities3' section of the application configuration file.
        /// </summary>
        public DB_SMPEntities3() : base("name=DB_SMPEntities3", "DB_SMPEntities3")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DB_SMPEntities3 object.
        /// </summary>
        public DB_SMPEntities3(string connectionString) : base(connectionString, "DB_SMPEntities3")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DB_SMPEntities3 object.
        /// </summary>
        public DB_SMPEntities3(EntityConnection connection) : base(connection, "DB_SMPEntities3")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TB_CAT> TB_CAT
        {
            get
            {
                if ((_TB_CAT == null))
                {
                    _TB_CAT = base.CreateObjectSet<TB_CAT>("TB_CAT");
                }
                return _TB_CAT;
            }
        }
        private ObjectSet<TB_CAT> _TB_CAT;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TB_CUS> TB_CUS
        {
            get
            {
                if ((_TB_CUS == null))
                {
                    _TB_CUS = base.CreateObjectSet<TB_CUS>("TB_CUS");
                }
                return _TB_CUS;
            }
        }
        private ObjectSet<TB_CUS> _TB_CUS;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TB_PUR> TB_PUR
        {
            get
            {
                if ((_TB_PUR == null))
                {
                    _TB_PUR = base.CreateObjectSet<TB_PUR>("TB_PUR");
                }
                return _TB_PUR;
            }
        }
        private ObjectSet<TB_PUR> _TB_PUR;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TB_SELL> TB_SELL
        {
            get
            {
                if ((_TB_SELL == null))
                {
                    _TB_SELL = base.CreateObjectSet<TB_SELL>("TB_SELL");
                }
                return _TB_SELL;
            }
        }
        private ObjectSet<TB_SELL> _TB_SELL;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TB_SUP> TB_SUP
        {
            get
            {
                if ((_TB_SUP == null))
                {
                    _TB_SUP = base.CreateObjectSet<TB_SUP>("TB_SUP");
                }
                return _TB_SUP;
            }
        }
        private ObjectSet<TB_SUP> _TB_SUP;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TBUSER> TBUSERs
        {
            get
            {
                if ((_TBUSERs == null))
                {
                    _TBUSERs = base.CreateObjectSet<TBUSER>("TBUSERs");
                }
                return _TBUSERs;
            }
        }
        private ObjectSet<TBUSER> _TBUSERs;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TB_CAT EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTB_CAT(TB_CAT tB_CAT)
        {
            base.AddObject("TB_CAT", tB_CAT);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TB_CUS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTB_CUS(TB_CUS tB_CUS)
        {
            base.AddObject("TB_CUS", tB_CUS);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TB_PUR EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTB_PUR(TB_PUR tB_PUR)
        {
            base.AddObject("TB_PUR", tB_PUR);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TB_SELL EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTB_SELL(TB_SELL tB_SELL)
        {
            base.AddObject("TB_SELL", tB_SELL);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TB_SUP EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTB_SUP(TB_SUP tB_SUP)
        {
            base.AddObject("TB_SUP", tB_SUP);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TBUSERs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTBUSERs(TBUSER tBUSER)
        {
            base.AddObject("TBUSERs", tBUSER);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_SMPModel", Name="TB_CAT")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TB_CAT : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TB_CAT object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static TB_CAT CreateTB_CAT(global::System.Int32 id)
        {
            TB_CAT tB_CAT = new TB_CAT();
            tB_CAT.ID = id;
            return tB_CAT;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CAT_Name
        {
            get
            {
                return _CAT_Name;
            }
            set
            {
                OnCAT_NameChanging(value);
                ReportPropertyChanging("CAT_Name");
                _CAT_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CAT_Name");
                OnCAT_NameChanged();
            }
        }
        private global::System.String _CAT_Name;
        partial void OnCAT_NameChanging(global::System.String value);
        partial void OnCAT_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] CAT_Cover
        {
            get
            {
                return StructuralObject.GetValidValue(_CAT_Cover);
            }
            set
            {
                OnCAT_CoverChanging(value);
                ReportPropertyChanging("CAT_Cover");
                _CAT_Cover = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CAT_Cover");
                OnCAT_CoverChanged();
            }
        }
        private global::System.Byte[] _CAT_Cover;
        partial void OnCAT_CoverChanging(global::System.Byte[] value);
        partial void OnCAT_CoverChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_SMPModel", "FK_TB_PUR_TB_CAT", "TB_PUR")]
        public EntityCollection<TB_PUR> TB_PUR
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TB_PUR>("DB_SMPModel.FK_TB_PUR_TB_CAT", "TB_PUR");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TB_PUR>("DB_SMPModel.FK_TB_PUR_TB_CAT", "TB_PUR", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_SMPModel", Name="TB_CUS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TB_CUS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TB_CUS object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static TB_CUS CreateTB_CUS(global::System.Int32 id)
        {
            TB_CUS tB_CUS = new TB_CUS();
            tB_CUS.ID = id;
            return tB_CUS;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sup_Name
        {
            get
            {
                return _Sup_Name;
            }
            set
            {
                OnSup_NameChanging(value);
                ReportPropertyChanging("Sup_Name");
                _Sup_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Sup_Name");
                OnSup_NameChanged();
            }
        }
        private global::System.String _Sup_Name;
        partial void OnSup_NameChanging(global::System.String value);
        partial void OnSup_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sup_Phone
        {
            get
            {
                return _Sup_Phone;
            }
            set
            {
                OnSup_PhoneChanging(value);
                ReportPropertyChanging("Sup_Phone");
                _Sup_Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Sup_Phone");
                OnSup_PhoneChanged();
            }
        }
        private global::System.String _Sup_Phone;
        partial void OnSup_PhoneChanging(global::System.String value);
        partial void OnSup_PhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sup_Email
        {
            get
            {
                return _Sup_Email;
            }
            set
            {
                OnSup_EmailChanging(value);
                ReportPropertyChanging("Sup_Email");
                _Sup_Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Sup_Email");
                OnSup_EmailChanged();
            }
        }
        private global::System.String _Sup_Email;
        partial void OnSup_EmailChanging(global::System.String value);
        partial void OnSup_EmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Sup_Image
        {
            get
            {
                return StructuralObject.GetValidValue(_Sup_Image);
            }
            set
            {
                OnSup_ImageChanging(value);
                ReportPropertyChanging("Sup_Image");
                _Sup_Image = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Sup_Image");
                OnSup_ImageChanged();
            }
        }
        private global::System.Byte[] _Sup_Image;
        partial void OnSup_ImageChanging(global::System.Byte[] value);
        partial void OnSup_ImageChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_SMPModel", Name="TB_PUR")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TB_PUR : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TB_PUR object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="pur_Cat">Initial value of the Pur_Cat property.</param>
        public static TB_PUR CreateTB_PUR(global::System.Int32 id, global::System.String pur_Cat)
        {
            TB_PUR tB_PUR = new TB_PUR();
            tB_PUR.ID = id;
            tB_PUR.Pur_Cat = pur_Cat;
            return tB_PUR;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Cat_id
        {
            get
            {
                return _Cat_id;
            }
            set
            {
                OnCat_idChanging(value);
                ReportPropertyChanging("Cat_id");
                _Cat_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cat_id");
                OnCat_idChanged();
            }
        }
        private Nullable<global::System.Int32> _Cat_id;
        partial void OnCat_idChanging(Nullable<global::System.Int32> value);
        partial void OnCat_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Supp_id
        {
            get
            {
                return _Supp_id;
            }
            set
            {
                OnSupp_idChanging(value);
                ReportPropertyChanging("Supp_id");
                _Supp_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Supp_id");
                OnSupp_idChanged();
            }
        }
        private Nullable<global::System.Int32> _Supp_id;
        partial void OnSupp_idChanging(Nullable<global::System.Int32> value);
        partial void OnSupp_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pur_Name
        {
            get
            {
                return _Pur_Name;
            }
            set
            {
                OnPur_NameChanging(value);
                ReportPropertyChanging("Pur_Name");
                _Pur_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Pur_Name");
                OnPur_NameChanged();
            }
        }
        private global::System.String _Pur_Name;
        partial void OnPur_NameChanging(global::System.String value);
        partial void OnPur_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pur_Type
        {
            get
            {
                return _Pur_Type;
            }
            set
            {
                OnPur_TypeChanging(value);
                ReportPropertyChanging("Pur_Type");
                _Pur_Type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Pur_Type");
                OnPur_TypeChanged();
            }
        }
        private global::System.String _Pur_Type;
        partial void OnPur_TypeChanging(global::System.String value);
        partial void OnPur_TypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Pur_Cat
        {
            get
            {
                return _Pur_Cat;
            }
            set
            {
                OnPur_CatChanging(value);
                ReportPropertyChanging("Pur_Cat");
                _Pur_Cat = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Pur_Cat");
                OnPur_CatChanged();
            }
        }
        private global::System.String _Pur_Cat;
        partial void OnPur_CatChanging(global::System.String value);
        partial void OnPur_CatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pur_Supp
        {
            get
            {
                return _Pur_Supp;
            }
            set
            {
                OnPur_SuppChanging(value);
                ReportPropertyChanging("Pur_Supp");
                _Pur_Supp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Pur_Supp");
                OnPur_SuppChanged();
            }
        }
        private global::System.String _Pur_Supp;
        partial void OnPur_SuppChanging(global::System.String value);
        partial void OnPur_SuppChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pur_Det
        {
            get
            {
                return _Pur_Det;
            }
            set
            {
                OnPur_DetChanging(value);
                ReportPropertyChanging("Pur_Det");
                _Pur_Det = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Pur_Det");
                OnPur_DetChanged();
            }
        }
        private global::System.String _Pur_Det;
        partial void OnPur_DetChanging(global::System.String value);
        partial void OnPur_DetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Pur_Buy
        {
            get
            {
                return _Pur_Buy;
            }
            set
            {
                OnPur_BuyChanging(value);
                ReportPropertyChanging("Pur_Buy");
                _Pur_Buy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Pur_Buy");
                OnPur_BuyChanged();
            }
        }
        private Nullable<global::System.Double> _Pur_Buy;
        partial void OnPur_BuyChanging(Nullable<global::System.Double> value);
        partial void OnPur_BuyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Pur_Qt
        {
            get
            {
                return _Pur_Qt;
            }
            set
            {
                OnPur_QtChanging(value);
                ReportPropertyChanging("Pur_Qt");
                _Pur_Qt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Pur_Qt");
                OnPur_QtChanged();
            }
        }
        private Nullable<global::System.Double> _Pur_Qt;
        partial void OnPur_QtChanging(Nullable<global::System.Double> value);
        partial void OnPur_QtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Pur_Tsell
        {
            get
            {
                return _Pur_Tsell;
            }
            set
            {
                OnPur_TsellChanging(value);
                ReportPropertyChanging("Pur_Tsell");
                _Pur_Tsell = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Pur_Tsell");
                OnPur_TsellChanged();
            }
        }
        private Nullable<global::System.Double> _Pur_Tsell;
        partial void OnPur_TsellChanging(Nullable<global::System.Double> value);
        partial void OnPur_TsellChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Pur_Tbuy
        {
            get
            {
                return _Pur_Tbuy;
            }
            set
            {
                OnPur_TbuyChanging(value);
                ReportPropertyChanging("Pur_Tbuy");
                _Pur_Tbuy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Pur_Tbuy");
                OnPur_TbuyChanged();
            }
        }
        private Nullable<global::System.Double> _Pur_Tbuy;
        partial void OnPur_TbuyChanging(Nullable<global::System.Double> value);
        partial void OnPur_TbuyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Pur_TRev
        {
            get
            {
                return _Pur_TRev;
            }
            set
            {
                OnPur_TRevChanging(value);
                ReportPropertyChanging("Pur_TRev");
                _Pur_TRev = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Pur_TRev");
                OnPur_TRevChanged();
            }
        }
        private Nullable<global::System.Double> _Pur_TRev;
        partial void OnPur_TRevChanging(Nullable<global::System.Double> value);
        partial void OnPur_TRevChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Purr_Tbuy
        {
            get
            {
                return _Purr_Tbuy;
            }
            set
            {
                OnPurr_TbuyChanging(value);
                ReportPropertyChanging("Purr_Tbuy");
                _Purr_Tbuy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Purr_Tbuy");
                OnPurr_TbuyChanged();
            }
        }
        private Nullable<global::System.Double> _Purr_Tbuy;
        partial void OnPurr_TbuyChanging(Nullable<global::System.Double> value);
        partial void OnPurr_TbuyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Pur_Sell
        {
            get
            {
                return _Pur_Sell;
            }
            set
            {
                OnPur_SellChanging(value);
                ReportPropertyChanging("Pur_Sell");
                _Pur_Sell = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Pur_Sell");
                OnPur_SellChanged();
            }
        }
        private Nullable<global::System.Double> _Pur_Sell;
        partial void OnPur_SellChanging(Nullable<global::System.Double> value);
        partial void OnPur_SellChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_SMPModel", "FK_TB_PUR_TB_CAT", "TB_CAT")]
        public TB_CAT TB_CAT
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_CAT>("DB_SMPModel.FK_TB_PUR_TB_CAT", "TB_CAT").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_CAT>("DB_SMPModel.FK_TB_PUR_TB_CAT", "TB_CAT").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TB_CAT> TB_CATReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_CAT>("DB_SMPModel.FK_TB_PUR_TB_CAT", "TB_CAT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TB_CAT>("DB_SMPModel.FK_TB_PUR_TB_CAT", "TB_CAT", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_SMPModel", "FK_TB_PUR_TB_SUP", "TB_SUP")]
        public TB_SUP TB_SUP
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_SUP>("DB_SMPModel.FK_TB_PUR_TB_SUP", "TB_SUP").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_SUP>("DB_SMPModel.FK_TB_PUR_TB_SUP", "TB_SUP").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TB_SUP> TB_SUPReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TB_SUP>("DB_SMPModel.FK_TB_PUR_TB_SUP", "TB_SUP");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TB_SUP>("DB_SMPModel.FK_TB_PUR_TB_SUP", "TB_SUP", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_SMPModel", Name="TB_SELL")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TB_SELL : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TB_SELL object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static TB_SELL CreateTB_SELL(global::System.Int32 id)
        {
            TB_SELL tB_SELL = new TB_SELL();
            tB_SELL.ID = id;
            return tB_SELL;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sell_Name
        {
            get
            {
                return _Sell_Name;
            }
            set
            {
                OnSell_NameChanging(value);
                ReportPropertyChanging("Sell_Name");
                _Sell_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Sell_Name");
                OnSell_NameChanged();
            }
        }
        private global::System.String _Sell_Name;
        partial void OnSell_NameChanging(global::System.String value);
        partial void OnSell_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sell_Cus
        {
            get
            {
                return _Sell_Cus;
            }
            set
            {
                OnSell_CusChanging(value);
                ReportPropertyChanging("Sell_Cus");
                _Sell_Cus = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Sell_Cus");
                OnSell_CusChanged();
            }
        }
        private global::System.String _Sell_Cus;
        partial void OnSell_CusChanging(global::System.String value);
        partial void OnSell_CusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Sell_Price
        {
            get
            {
                return _Sell_Price;
            }
            set
            {
                OnSell_PriceChanging(value);
                ReportPropertyChanging("Sell_Price");
                _Sell_Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sell_Price");
                OnSell_PriceChanged();
            }
        }
        private Nullable<global::System.Double> _Sell_Price;
        partial void OnSell_PriceChanging(Nullable<global::System.Double> value);
        partial void OnSell_PriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Sell_Qt
        {
            get
            {
                return _Sell_Qt;
            }
            set
            {
                OnSell_QtChanging(value);
                ReportPropertyChanging("Sell_Qt");
                _Sell_Qt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sell_Qt");
                OnSell_QtChanged();
            }
        }
        private Nullable<global::System.Double> _Sell_Qt;
        partial void OnSell_QtChanging(Nullable<global::System.Double> value);
        partial void OnSell_QtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Sell_TPrice
        {
            get
            {
                return _Sell_TPrice;
            }
            set
            {
                OnSell_TPriceChanging(value);
                ReportPropertyChanging("Sell_TPrice");
                _Sell_TPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sell_TPrice");
                OnSell_TPriceChanged();
            }
        }
        private Nullable<global::System.Double> _Sell_TPrice;
        partial void OnSell_TPriceChanging(Nullable<global::System.Double> value);
        partial void OnSell_TPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Sell_Date
        {
            get
            {
                return _Sell_Date;
            }
            set
            {
                OnSell_DateChanging(value);
                ReportPropertyChanging("Sell_Date");
                _Sell_Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sell_Date");
                OnSell_DateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Sell_Date;
        partial void OnSell_DateChanging(Nullable<global::System.DateTime> value);
        partial void OnSell_DateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_SMPModel", Name="TB_SUP")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TB_SUP : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TB_SUP object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static TB_SUP CreateTB_SUP(global::System.Int32 id)
        {
            TB_SUP tB_SUP = new TB_SUP();
            tB_SUP.ID = id;
            return tB_SUP;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sup_Name
        {
            get
            {
                return _Sup_Name;
            }
            set
            {
                OnSup_NameChanging(value);
                ReportPropertyChanging("Sup_Name");
                _Sup_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Sup_Name");
                OnSup_NameChanged();
            }
        }
        private global::System.String _Sup_Name;
        partial void OnSup_NameChanging(global::System.String value);
        partial void OnSup_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sup_Phone
        {
            get
            {
                return _Sup_Phone;
            }
            set
            {
                OnSup_PhoneChanging(value);
                ReportPropertyChanging("Sup_Phone");
                _Sup_Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Sup_Phone");
                OnSup_PhoneChanged();
            }
        }
        private global::System.String _Sup_Phone;
        partial void OnSup_PhoneChanging(global::System.String value);
        partial void OnSup_PhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sup_Email
        {
            get
            {
                return _Sup_Email;
            }
            set
            {
                OnSup_EmailChanging(value);
                ReportPropertyChanging("Sup_Email");
                _Sup_Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Sup_Email");
                OnSup_EmailChanged();
            }
        }
        private global::System.String _Sup_Email;
        partial void OnSup_EmailChanging(global::System.String value);
        partial void OnSup_EmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Sup_Image
        {
            get
            {
                return StructuralObject.GetValidValue(_Sup_Image);
            }
            set
            {
                OnSup_ImageChanging(value);
                ReportPropertyChanging("Sup_Image");
                _Sup_Image = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Sup_Image");
                OnSup_ImageChanged();
            }
        }
        private global::System.Byte[] _Sup_Image;
        partial void OnSup_ImageChanging(global::System.Byte[] value);
        partial void OnSup_ImageChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_SMPModel", "FK_TB_PUR_TB_SUP", "TB_PUR")]
        public EntityCollection<TB_PUR> TB_PUR
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TB_PUR>("DB_SMPModel.FK_TB_PUR_TB_SUP", "TB_PUR");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TB_PUR>("DB_SMPModel.FK_TB_PUR_TB_SUP", "TB_PUR", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_SMPModel", Name="TBUSER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBUSER : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TBUSER object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static TBUSER CreateTBUSER(global::System.Int32 id)
        {
            TBUSER tBUSER = new TBUSER();
            tBUSER.ID = id;
            return tBUSER;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Passowrd
        {
            get
            {
                return _Passowrd;
            }
            set
            {
                OnPassowrdChanging(value);
                ReportPropertyChanging("Passowrd");
                _Passowrd = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Passowrd");
                OnPassowrdChanged();
            }
        }
        private global::System.String _Passowrd;
        partial void OnPassowrdChanging(global::System.String value);
        partial void OnPassowrdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Image
        {
            get
            {
                return StructuralObject.GetValidValue(_Image);
            }
            set
            {
                OnImageChanging(value);
                ReportPropertyChanging("Image");
                _Image = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Image");
                OnImageChanged();
            }
        }
        private global::System.Byte[] _Image;
        partial void OnImageChanging(global::System.Byte[] value);
        partial void OnImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Rol
        {
            get
            {
                return _Rol;
            }
            set
            {
                OnRolChanging(value);
                ReportPropertyChanging("Rol");
                _Rol = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Rol");
                OnRolChanged();
            }
        }
        private global::System.String _Rol;
        partial void OnRolChanging(global::System.String value);
        partial void OnRolChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String stt
        {
            get
            {
                return _stt;
            }
            set
            {
                OnsttChanging(value);
                ReportPropertyChanging("stt");
                _stt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("stt");
                OnsttChanged();
            }
        }
        private global::System.String _stt;
        partial void OnsttChanging(global::System.String value);
        partial void OnsttChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();

        #endregion

    
    }

    #endregion

    
}
